### PR TITLE
extended initialize to accept custom server

### PR DESCRIPTION
**Pull request by philsippl**
This allows using the module with the open source parse server.
https://github.com/ParsePlatform/parse-server

### CODE REVIEW

**Comment by giovanymoreno** [comment]
This is exactly what I was looking for, but I think you are missing the `getUrl()` method from `ParseBatchCommand` class.

**Comment by thiagolocatelli** [comment]
merged

**Comment by raytrask** [comment]
Love this change!

I assume we need to setup a Rest key (which is not default out of the box) for this code to work.  Also I am assuming the serverPath is fully qualified URL, e.g. http://...../parse.

Are these assumptions correct?

**Comment by SeloSlav** [comment]
How can I get this working in my project? Can I just change the API_ENDPOINT value in ParseConstants.java  to https://parseapi.back4app.com, for example?

**Comment by philsippl** [comment]
@santafebound Just do an initialization at the beginning:
`Parse.initialize("appid", "", "http://parseserver/parse");`

**Pull request merged**
